-- This file is automatically generated using maintenance/generateSchemaSql.php.
-- Source: db/issuetrackerlinks_issues.json
-- Do not modify this file directly.
-- See https://www.mediawiki.org/wiki/Manual:Schema_changes
CREATE TABLE /*_*/issuetrackerlinks_issues (
  itli_page_title VARCHAR(255) NOT NULL,
  itli_page_namespace VARCHAR(255) NOT NULL,
  itli_wiki_id VARCHAR(255) NOT NULL,
  itli_type VARCHAR(255) NOT NULL,
  itli_data_provider VARCHAR(255) NOT NULL,
  itli_params BLOB DEFAULT NULL
);
