-- This file is automatically generated using maintenance/generateSchemaSql.php.
-- Source: db/issuetrackerlinks_auth_tokens.json
-- Do not modify this file directly.
-- See https://www.mediawiki.org/wiki/Manual:Schema_changes
CREATE TABLE /*_*/issuetrackerlinks_auth_tokens (
  itlat_user INTEGER UNSIGNED NOT NULL,
  itlat_provider VARCHAR(255) NOT NULL,
  itlat_auth_data BLOB NOT NULL
);

CREATE UNIQUE INDEX issuetrackerlinks_auth_tokens_user_provider ON /*_*/issuetrackerlinks_auth_tokens (itlat_user, itlat_provider);
