-- This file is automatically generated using maintenance/generateSchemaSql.php.
-- Source: db/issuetrackerlinks_provider_config.json
-- Do not modify this file directly.
-- See https://www.mediawiki.org/wiki/Manual:Schema_changes
CREATE TABLE issuetrackerlinks_provider_config (
  itlpc_id VARCHAR(32) NOT NULL,
  itlpc_name VARCHAR(255) NOT NULL,
  itlpc_type VARCHAR(255) NOT NULL,
  itlpc_data TEXT NOT NULL,
  PRIMARY KEY(itlpc_id, itlpc_name)
);
